### ISSUE TITLE
Stop timer from outside of application

### ISSUE THREAD

**Issue by viq** [olpeh/wht#25]
I would like to automate it as much as possible. It's already pretty easy to start the timer (via situations, start timer with start of app, start app when connected to office wireless), but it would be helpful to also be able to automate the stop of the timer, eg when leaving the wireless. Situations is able to run a command when something happens, but that would require being able to stop a timer via a command.

**Comment by ojhaapala** [comment]
Awesome idea!

**Comment by jesseuitto** [comment]
I would like if after phone call program asks if I want to mark that phone call as an break, or include it in some project.  It's n

**Comment by jesseuitto** [comment]
Phone call is not always related to current on going task, so it would be nice if that time could be separated into other project if necessary.

**Comment by olpeh** [comment]
@jesseuitto I'm not sure if I would like to have an app that "reads" my phone calls and so on. Also it would require quite a lot of work. 
Maybe if situations is able to do that and then run a command for working hours tracker?

**Comment by olpeh** [comment]
This feature is actually implemented for a while ago.
You can use commands to control the timer. See https://github.com/olpeh/wht#startup-commands
Starting the timer: harbour-workinghourstracker --start
 Stopping the timer: harbour-workinghourstracker --stop

More advanced features coming. And this is not perfect because it starts another instance of the app if it was already running.

Tip: Use Situations app to run these commands whenever needed.
