### ISSUE TITLE
Summation is not working

### ISSUE THREAD

**Issue by krzyc** [olpeh/wht#76]
After 62f5d331bc27bdf423768be8ba43ed0dd24c368b summation is not working, because breakDuration is set to NULL instead of 0.
I have prepared a fix #77 **but I think it is not correct.**
We should probably add db fix which updates NULL to 0 and set this field as NOT NULL.

**Comment by olpeh** [comment]
I feel it's a bit scary to touch the db schema because of this because it can easily cause more problems. I'll create a update that sets it to 0 and I'll probably revert https://github.com/olpeh/wht/commit/62f5d331bc27bdf423768be8ba43ed0dd24c368b and set them to 0 instead of leaving out if less than a minute.
